version: "3"

services:
 minio:
   container_name: minio
   image: minio/minio:latest
   command: server --console-address ":9001" /data/
   ports:
     - "9000:9000"
     - "9001:9001"
   environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123456789
   volumes:
     - minio-storage:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3
 rabbitmq:
   image: rabbitmq:3.10.7-management
   container_name: rabbitmq
   hostname: rabbitmq
   restart: always
   environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
   volumes:
     - ./rabbitmq:/var/lib/rabbitmq
   ports:
     - 15672:15672
     - 5672:5672


volumes:
 minio-storage: